#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_DIR="${ROOT_DIR}/libs/api-client/src"
KIMAI_OUTPUT="${OUTPUT_DIR}/kimai.ts"
TIMETREX_OUTPUT="${OUTPUT_DIR}/timetrex.ts"

KIMAI_SPEC_URL="${KIMAI_SPEC_URL:-http://localhost:8001/api/doc.json}"
TIMETREX_SPEC_URL="${TIMETREX_SPEC_URL:-http://localhost:8002/api/v1/doc.json}"

echo "============================================"
echo "  ServiceCore API Client Generator"
echo "============================================"
echo ""

ensure_output_dir() {
  mkdir -p "${OUTPUT_DIR}"
}

is_available() {
  local url="$1"
  curl -sf "${url}" > /dev/null 2>&1
}

generate_with_nswag() {
  local input_url="$1"
  local output_file="$2"
  npx --yes nswag openapi2tsclient \
    "/input:${input_url}" \
    "/output:${output_file}" \
    /generateClientClasses:true \
    /template:Angular
}

write_kimai_fallback() {
  cat > "${KIMAI_OUTPUT}" <<'EOF'
/* eslint-disable */
/**
 * AUTO-GENERATED FILE.
 * Generated by `tools/generate-api-clients.sh` fallback generator.
 * Do not edit manually.
 */

export interface KimaiClientConfig {
  baseUrl: string;
  apiToken?: string;
}

export type KimaiTimesheetPayload = Record<string, unknown>;
export type KimaiTimesheet = Record<string, unknown>;

export class KimaiApiClient {
  constructor(private readonly config: KimaiClientConfig) {}

  async listTimesheets(
    params: Record<string, string | number | boolean> = {}
  ): Promise<KimaiTimesheet[]> {
    const search = new URLSearchParams();
    for (const [key, value] of Object.entries(params)) {
      search.set(key, String(value));
    }
    const query = search.toString();
    return this.request<KimaiTimesheet[]>(
      `/api/timesheets${query ? `?${query}` : ''}`,
      { method: 'GET' }
    );
  }

  async getTimesheet(timesheetId: string): Promise<KimaiTimesheet> {
    return this.request<KimaiTimesheet>(`/api/timesheets/${timesheetId}`, {
      method: 'GET',
    });
  }

  async createTimesheet(
    payload: KimaiTimesheetPayload
  ): Promise<KimaiTimesheet> {
    return this.request<KimaiTimesheet>('/api/timesheets', {
      method: 'POST',
      body: payload,
    });
  }

  private async request<T>(
    path: string,
    options: { method: string; body?: unknown }
  ): Promise<T> {
    const response = await fetch(`${this.config.baseUrl}${path}`, {
      method: options.method,
      headers: {
        'Content-Type': 'application/json',
        ...(this.config.apiToken
          ? { Authorization: `Bearer ${this.config.apiToken}` }
          : {}),
      },
      body: options.body ? JSON.stringify(options.body) : undefined,
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`Kimai API request failed (${response.status}): ${text}`);
    }

    return (await response.json()) as T;
  }
}
EOF
}

write_timetrex_fallback() {
  cat > "${TIMETREX_OUTPUT}" <<'EOF'
/* eslint-disable */
/**
 * AUTO-GENERATED FILE.
 * Generated by `tools/generate-api-clients.sh` fallback generator.
 * Do not edit manually.
 */

export type TimeTrexApiMode = 'rest' | 'legacy_rpc';

export interface TimeTrexClientConfig {
  baseUrl: string;
  apiToken?: string;
  apiMode?: TimeTrexApiMode;
  rpcVersion?: string;
  sessionCookie?: string;
  csrfToken?: string;
}

export class TimeTrexApiClient {
  private readonly apiMode: TimeTrexApiMode;
  private readonly rpcVersion: string;

  constructor(private readonly config: TimeTrexClientConfig) {
    this.apiMode = config.apiMode ?? 'rest';
    this.rpcVersion = config.rpcVersion ?? '2';
  }

  async previewPayroll(payload: Record<string, unknown>): Promise<unknown> {
    if (this.apiMode === 'legacy_rpc') {
      return this.rpcRequest('APIPayPeriod', 'getPayPeriod', payload);
    }
    return this.request('/api/v1/payroll/preview', 'POST', payload);
  }

  async exportPayroll(payload: Record<string, unknown>): Promise<unknown> {
    if (this.apiMode === 'legacy_rpc') {
      return this.rpcRequest(
        'APIPayStubTransaction',
        'getPayStubTransaction',
        payload
      );
    }
    return this.request('/api/v1/payroll/export', 'POST', payload);
  }

  private async rpcRequest(
    className: string,
    methodName: string,
    payload: Record<string, unknown>
  ): Promise<unknown> {
    if (!this.config.sessionCookie || !this.config.csrfToken) {
      throw new Error(
        'sessionCookie and csrfToken are required in legacy_rpc mode'
      );
    }

    const query = new URLSearchParams({
      Class: className,
      Method: methodName,
      v: this.rpcVersion,
      MessageID: `${Date.now()}-${Math.random().toString(16).slice(2, 10)}`,
    });

    const body = new URLSearchParams({
      json: JSON.stringify({ 0: payload }),
    });

    const response = await fetch(
      `${this.config.baseUrl}/api/json/api.php?${query.toString()}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
          Accept: 'application/json, text/javascript, */*; q=0.01',
          'X-Requested-With': 'XMLHttpRequest',
          'X-CSRF-Token': this.config.csrfToken,
          Cookie: this.config.sessionCookie,
        },
        body: body.toString(),
      }
    );

    if (!response.ok) {
      const text = await response.text();
      throw new Error(
        `TimeTrex RPC request failed (${response.status}) [${className}.${methodName}]: ${text}`
      );
    }

    return response.json();
  }

  private async request(
    path: string,
    method: string,
    payload?: unknown
  ): Promise<unknown> {
    const response = await fetch(`${this.config.baseUrl}${path}`, {
      method,
      headers: {
        'Content-Type': 'application/json',
        ...(this.config.apiToken
          ? { Authorization: `Bearer ${this.config.apiToken}` }
          : {}),
      },
      body: payload ? JSON.stringify(payload) : undefined,
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(
        `TimeTrex API request failed (${response.status}): ${text}`
      );
    }

    return response.json();
  }
}
EOF
}

generate_client() {
  local name="$1"
  local spec_url="$2"
  local output_file="$3"
  local fallback_writer="$4"

  echo "[${name}] Checking OpenAPI spec: ${spec_url}"
  if is_available "${spec_url}"; then
    echo "[${name}] Spec reachable. Trying NSwag generation..."
    if generate_with_nswag "${spec_url}" "${output_file}"; then
      echo "[${name}] NSwag generation succeeded."
      return
    fi
    echo "[${name}] NSwag failed. Falling back to local generated client template."
  else
    echo "[${name}] Spec unavailable. Falling back to local generated client template."
  fi

  "${fallback_writer}"
  echo "[${name}] Fallback client written to ${output_file}"
}

ensure_output_dir
generate_client "Kimai" "${KIMAI_SPEC_URL}" "${KIMAI_OUTPUT}" write_kimai_fallback
generate_client "TimeTrex" "${TIMETREX_SPEC_URL}" "${TIMETREX_OUTPUT}" write_timetrex_fallback

echo ""
echo "============================================"
echo "  API client generation complete"
echo "  DO NOT EDIT generated files manually"
echo "============================================"
