/* eslint-disable */
/**
 * AUTO-GENERATED FILE.
 * Generated by `tools/generate-api-clients.sh` fallback generator.
 * Do not edit manually.
 */

export interface KimaiClientConfig {
  baseUrl: string;
  apiToken?: string;
}

export type KimaiTimesheetPayload = Record<string, unknown>;
export type KimaiTimesheet = Record<string, unknown>;

export class KimaiApiClient {
  constructor(private readonly config: KimaiClientConfig) {}

  async listTimesheets(
    params: Record<string, string | number | boolean> = {}
  ): Promise<KimaiTimesheet[]> {
    const search = new URLSearchParams();
    for (const [key, value] of Object.entries(params)) {
      search.set(key, String(value));
    }
    const query = search.toString();
    return this.request<KimaiTimesheet[]>(
      `/api/timesheets${query ? `?${query}` : ''}`,
      { method: 'GET' }
    );
  }

  async getTimesheet(timesheetId: string): Promise<KimaiTimesheet> {
    return this.request<KimaiTimesheet>(`/api/timesheets/${timesheetId}`, {
      method: 'GET',
    });
  }

  async createTimesheet(
    payload: KimaiTimesheetPayload
  ): Promise<KimaiTimesheet> {
    return this.request<KimaiTimesheet>('/api/timesheets', {
      method: 'POST',
      body: payload,
    });
  }

  private async request<T>(
    path: string,
    options: { method: string; body?: unknown }
  ): Promise<T> {
    const response = await fetch(`${this.config.baseUrl}${path}`, {
      method: options.method,
      headers: {
        'Content-Type': 'application/json',
        ...(this.config.apiToken
          ? { Authorization: `Bearer ${this.config.apiToken}` }
          : {}),
      },
      body: options.body ? JSON.stringify(options.body) : undefined,
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`Kimai API request failed (${response.status}): ${text}`);
    }

    return (await response.json()) as T;
  }
}
