/* eslint-disable */
/**
 * AUTO-GENERATED FILE.
 * Generated by `tools/generate-api-clients.sh` fallback generator.
 * Do not edit manually.
 */

export type TimeTrexApiMode = 'rest' | 'legacy_rpc';

export interface TimeTrexClientConfig {
  baseUrl: string;
  apiToken?: string;
  apiMode?: TimeTrexApiMode;
  rpcVersion?: string;
  sessionCookie?: string;
  csrfToken?: string;
}

export class TimeTrexApiClient {
  private readonly apiMode: TimeTrexApiMode;
  private readonly rpcVersion: string;

  constructor(private readonly config: TimeTrexClientConfig) {
    this.apiMode = config.apiMode ?? 'rest';
    this.rpcVersion = config.rpcVersion ?? '2';
  }

  async previewPayroll(payload: Record<string, unknown>): Promise<unknown> {
    if (this.apiMode === 'legacy_rpc') {
      return this.rpcRequest('APIPayPeriod', 'getPayPeriod', payload);
    }
    return this.request('/api/v1/payroll/preview', 'POST', payload);
  }

  async exportPayroll(payload: Record<string, unknown>): Promise<unknown> {
    if (this.apiMode === 'legacy_rpc') {
      return this.rpcRequest(
        'APIPayStubTransaction',
        'getPayStubTransaction',
        payload
      );
    }
    return this.request('/api/v1/payroll/export', 'POST', payload);
  }

  private async rpcRequest(
    className: string,
    methodName: string,
    payload: Record<string, unknown>
  ): Promise<unknown> {
    if (!this.config.sessionCookie || !this.config.csrfToken) {
      throw new Error(
        'sessionCookie and csrfToken are required in legacy_rpc mode'
      );
    }

    const query = new URLSearchParams({
      Class: className,
      Method: methodName,
      v: this.rpcVersion,
      MessageID: `${Date.now()}-${Math.random().toString(16).slice(2, 10)}`,
    });

    const body = new URLSearchParams({
      json: JSON.stringify({ 0: payload }),
    });

    const response = await fetch(
      `${this.config.baseUrl}/api/json/api.php?${query.toString()}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
          Accept: 'application/json, text/javascript, */*; q=0.01',
          'X-Requested-With': 'XMLHttpRequest',
          'X-CSRF-Token': this.config.csrfToken,
          Cookie: this.config.sessionCookie,
        },
        body: body.toString(),
      }
    );

    if (!response.ok) {
      const text = await response.text();
      throw new Error(
        `TimeTrex RPC request failed (${response.status}) [${className}.${methodName}]: ${text}`
      );
    }

    return response.json();
  }

  private async request(
    path: string,
    method: string,
    payload?: unknown
  ): Promise<unknown> {
    const response = await fetch(`${this.config.baseUrl}${path}`, {
      method,
      headers: {
        'Content-Type': 'application/json',
        ...(this.config.apiToken
          ? { Authorization: `Bearer ${this.config.apiToken}` }
          : {}),
      },
      body: payload ? JSON.stringify(payload) : undefined,
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(
        `TimeTrex API request failed (${response.status}): ${text}`
      );
    }

    return response.json();
  }
}
